### ISSUE TITLE
Requested metric: respiratory-volume-per-time

### ISSUE THREAD

**Issue by tsalo** [physiopy/phys2denoise#1]
Respiratory-volume-per-time (RVT) is a "breath-to-breath metric of respiratory variation," and can be used to generate a regressor for denoising fMRI data.

Per [Chang and Glover (2009)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2721281/?report=classic):

> First, peak detection was used to determine the maximum and minimum for each breath. The time series of maxima and minima (*max(t)* and *min(t)*) were then interpolated to the imaging TR. A time series of the breathing period (*T(t)*) was determined by taking the time difference between successive maxima, assigning the resulting value to the midpoint between the successive maxima, and interpolating the resulting time series to the imaging TR. The final RVT time series was then computed as *RVT(t) = (max(t) − min(t))/T(t)*.

A relevant metric is RPV convolved with a respiratory response function:

> In addition, *RVT(t)* was convolved with the RRF (Birn et al., 2008), forming a separate waveform (*RVT\*RRF(t)*).

RVT*RRF is also often lagged when used to denoise fMRI data.

**Comment by CesarCaballeroGaudes** [comment]
@tsalo thank you for the request. The implementation of this approach, along with its counterpart for variations in cardiac rate also described in this paper, is within our plans for phys2denoise

**Comment by tsalo** [comment]
I have functions sitting around for RV and RVT. I would be happy to open PRs for them to phys2denoise if you can give me an idea of how the package will be structured, so I know where to put them.

**Comment by smoia** [comment]
HI @tsalo ,
yes, that would be awesome!
I still need to think for a moment about how to structure this package.
If you have any suggestion don't hesitate to write down a line here or in Gitter!

**Comment by smoia** [comment]
The main thing I'm pondering is whether each metric should be on its own (i.e. the user should be able to invoke each of them via a command), if they should be argument of a general workflow (i.e. the user should call `phys2denoise -rvt`, for instance), or both.

**Comment by tsalo** [comment]
I personally would end up calling them within Python, but for the CLI it might be good to have an argument that can take multiple values (e.g., `phys2denoise --metrics rvt rpv rv`).

**Comment by CesarCaballeroGaudes** [comment]
Agree with this suggestion

**Comment by tsalo** [comment]
@smoia I posted about the infrastructure in [the Gitter channel](https://gitter.im/physiopy/phys2denoise), but can open a separate issue here if you'd prefer.
