### ISSUE TITLE
Script metric call in workflow

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2denoise#18]
Long story short:
- we have a bunch of metrics to call in the main workflow (see #4 and #7 for examples)
- we are going to ask the user to state which metric they want to compute using non-argument flags (see #14 for implementation)
- we could make a long list of `if metric_list contains metric then metric(args)` to call each metric
- HOWEVER, such list might grow exponentially (who knows how much)
- a much tidier approach is to do something pythonic: `for metric in metric_list do metric(args)`
- HOWEVER, each metric has different arguments in input
- HOWEVER, we can add `**kwarg` to all the metric calls so that we always pass all arguments without thinking about it too much, and those arguments that are not used will just be ignored (see example below)

What do you think @eurunuela @tsalo @62442katieb @CesarCaballeroGaudes @ineschh? 

```
In [1]: def hello(you='meh', age='42', **kwargs):                                                                                               
   ...:     print(f'Hi {you}, of age {age}')                                                                                                    
   ...: 
                                                                                                                                                
In [2]: hello(you='Arthur')                                                                                                                     
Hi Arthur, of age 42                                                                                                                            

In [3]: hello(you='Rick', age='46')                                                                                                             
Hi Rick, of age 46                                                                                                                              

In [4]: hello(you='Rick', age='46', blubba='bla')                                                                                               
Hi Rick, of age 46   
```

**Comment by eurunuela** [comment]
I don't think the example is very clear... how would users input the arguments?

**Comment by smoia** [comment]
Users that use the CLI will input flags with the parser in #14 .
For those that will import phys2denoise in python, we can write good docstrings that will explain that `**kwargs` are actaully not used.

**Comment by tsalo** [comment]
> a much tidier approach is to do something pythonic: `for metric in metric_list do metric(args)`

For the actual implementation, you need to go from the metric string to the metric function. You'd need to use either a dictionary mapping metric strings to functions (👍) or `eval` (👎).

However, idiomatic Python recommends explicit over implicit. Passing around `**kwargs` to all of the functions isn't very Pythonic, IMHO. 

We could probably use `inspect`, though, to get each function's signature and filter the available arguments in the workflow before feeding them into each function. It's still kind of scary on the workflow side, but the individual functions would remain explicit, which I consider very important as someone who will want to use those directly.

**Comment by smoia** [comment]
> For the actual implementation, you need to go from the metric string to the metric function. You'd need to use either a dictionary mapping metric strings to functions (+1) or `eval` (-1).

Wouldn't a simple import of all metrics in the parser (and then `assign_const=function`) be enough?
I like dictionaries otherwise! 

> We could probably use `inspect`, though, to [get each function's signature](https://docs.python.org/3/library/inspect.html#introspecting-callables-with-the-signature-object) and filter the available arguments in the workflow before feeding them into each function. It's still kind of scary on the workflow side, but the individual functions would remain explicit, which I consider very important as someone who will want to use those directly.

Uuuuh this looks like a strong option, I like it! Let me see how to implement it!

> I think the individual metric functions should be considered user-facing. Not everyone will want to use the workflow.

What do you mean with this? Do you mean that each individual metric should have a CLI, or that they should be intended to be used with python import?
In the second case, I guess that using inspect will be enough to avoid the `kwargs`, but it any case it wouldn't be much different than using a seaborn or a matplotlib function (although yes, in seaborn and matplotlib **kwargs is actually used, and not just a way to send some variables to waste).
In the first case, I see a lot of code duplication or a lot of functions for utility code, for not much more than what we could offer with a single workflow.

**Comment by tsalo** [comment]
> Wouldn't a simple import of all metrics in the parser (and then `assign_const=function`) be enough?

I hadn't even considered that! That sounds pretty cool, although I'm supportive of anything that avoids `eval`.

> What do you mean with this? Do you mean that each individual metric should have a CLI, or that they should be intended to be used with python import?

I don't think it would be good to have separate CLIs. I meant more that the metric functions should be (1) public, (2) well-documented, (3) present in the documentation, (4) they should use arrays instead of complex objects, whenever possible, and (5) they should have explicit inputs and outputs (instead of `kwargs`). I think we'd discussed (4) prior to this issue, and (1-3) are pretty uncontroversial.
