### ISSUE TITLE
Requested metric: respiratory variance

### ISSUE THREAD

**Issue by tsalo** [physiopy/phys2denoise#2]
Respiratory variance (RV) is, like RVT, used to measure variability of the respiratory trace. This regressor, especially when convolved with a respiratory response function (RRF), can be used to denoise fMRI data.

Per [Power et al. (2018) (appendix)](https://www.pnas.org/content/115/9/E2105.short):

> Second, the RV (respiratory variance) measure was created from the standard deviation of the respiratory trace within a 6-second window (following (7)), and this trace was lagged back 3 seconds and forward 3 seconds to create 3 regressors, and each of these regressors was convolved with the RRF defined above for a total of 6 respiratory regressors.

**Comment by CesarCaballeroGaudes** [comment]
The implementation of this approach is within our plans for phys2denoise. Keep tuned.
