### ISSUE TITLE
OHBM 2021 abstract submission

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2denoise#25]
This is related to physiopy/phys2bids#380.

OHBM abstract submission deadline is close, and if we submit two abstracts, one would be for `phys2denoise`.
However, that means pulling together and closing all these PRs we have open. I was thinking we could meet and do a sort of code sprint of one day before the 1st of February? Who would be in for that, @physiopy/all?

I'd be happy to take care of writing this abstract (also possible to do multiple authors)!

**Comment by smoia** [comment]
Tagging in particular @tsalo @rzlim08 @ineschh @CesarCaballeroGaudes

**Comment by tsalo** [comment]
I'm very interested in getting some of these metrics supported (less so the CPM and Hilbert RVT), so I'd be happy to help.

**Comment by rzlim08** [comment]
I wouldn't mind helping pull in these PRs. I don't know what my availability will be like because I have another submission to work on, but I think it can get done.
