### ISSUE TITLE
Requested metric: respiratory pattern variability

### ISSUE THREAD

**Issue by tsalo** [physiopy/phys2denoise#3]
Respiratory pattern variability (RPV) is a run-level metric created by in [Power et al. (2018)](https://www.pnas.org/content/115/9/E2105.short). The metric can also be calculated as a time series using a window, which in [Power et al. (2019)](https://www.sciencedirect.com/science/article/pii/S1053811919308250?dgcid=author#bib34) is referred to as ENV.

Per [Power et al. (2018)](https://www.pnas.org/content/115/9/E2105.short):

> To capture the variability of the respiratory patterns, the respiratory belt waveforms (which are in arbitrary units) were z-scored, the envelope of the resulting waveform was calculated, and the SD of this envelope was then calculated.

From [Power et al. (2019)](https://www.sciencedirect.com/science/article/pii/S1053811919308250?dgcid=author#bib34):

> These include respiration variation (RV), which is the standard deviation of the belt trace within a (6-s) window (Chang et al., 2009), **the envelope of the respiratory trace (over a 10-s window, ENV)** (Power et al., 2018), and the change in belt magnitude over a breath cycle (respiratory volume per time, RVT) (Birn et al., 2006).

**Comment by smoia** [comment]
@CesarCaballeroGaudes , do we have this in our plans already?
It would be good to add it!
