### ISSUE TITLE
Fix window calculation in env

### ISSUE THREAD

**Issue by rzlim08** [physiopy/phys2denoise#33]
https://github.com/physiopy/phys2denoise/blob/cfced3b47e7e7e4254e775cdfbc448e4c7cb15b0/phys2denoise/metrics/chest_belt.py#L95

@tsalo just adding some tests right now, but I think the window calculation for ENV needs to be looked at here. I'm not sure, but I don't think dividing by the out_samplerate is right. Also, I think it needs to be cast to an int.

**Comment by tsalo** [comment]
Agreed. Thanks!

**Comment by rzlim08** [comment]
actually I just saw that you've fixed it in your latest PR, sorry I missed that!
